name: pandocConvertor

on: push

jobs:
  convertViaPandoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Check out files to work on them
      - name: Confirm file names
        run: echo "${{job.convertViaPandoc.with}}"
      - uses: docker://pandoc/core:2.9
        id: pandocConvert
        name: Convert HTML to Jira MD
        with:
          args: >-  # allows you to break string into multiple lines
            --from html 
            --to jira
            --output=output/test.md 
            ${{ steps.files_list.outputs.files }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
