name: pandocConvertor

on: push

jobs:
  convertViaPandoc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Check out files to work on them
      - name: Confirm file names
        run: echo "${{job.convertViaPandoc.with}}"
      - uses: docker://pandoc/core:2.9
        id: pandocConvert
        name: Convert HTML to Jira MD
        with:
          args: "pandoc --from html --to jira test.html"
      - name: Get result
        run: echo "${{steps.pandocConvert.outputs.result}}" > test.html
      - name: Upload file
        id: uploadFile
        uses: actions/upload-artifact@v3
      - name: Echo upload location
        run: echo ${{steps.uploadFile.outputs.upload-path}}