name: pandocConvertor

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        name: Check out files to work on them
      - uses: docker://pandoc/core:2.9
        name: Convert HTML to Jira MD
        with:
          args: "pandoc --from html --to jira --output file2.md file2.html" # gets appended to pandoc command
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: 'file2.md'
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}